# Generated by Django 5.1.3 on 2024-11-15 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BondYield",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("us_10y", models.FloatField(null=True, verbose_name="US 10Y")),
                ("us_2y", models.FloatField(null=True, verbose_name="US 2Y")),
                (
                    "us_spread",
                    models.FloatField(null=True, verbose_name="2s10s Spread"),
                ),
            ],
            options={
                "verbose_name": "채권 수익률",
                "verbose_name_plural": "채권 수익률들",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Commodity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("gold", models.FloatField(null=True, verbose_name="Gold")),
                ("wti", models.FloatField(null=True, verbose_name="WTI")),
                ("bitcoin", models.FloatField(null=True, verbose_name="Bitcoin")),
            ],
            options={
                "verbose_name": "원자재",
                "verbose_name_plural": "원자재들",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="EconomicCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indicator",
                    models.CharField(
                        choices=[
                            ("cpi", "CPI"),
                            ("pce", "PCE"),
                            ("gdp", "GDP"),
                            ("unemployment", "실업률"),
                            ("pmi", "PMI"),
                        ],
                        max_length=20,
                        verbose_name="경제지표",
                    ),
                ),
                ("release_date", models.DateField(verbose_name="발표일")),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "월간"),
                            ("quarterly", "분기"),
                            ("annual", "연간"),
                        ],
                        max_length=10,
                        verbose_name="발표주기",
                    ),
                ),
                (
                    "previous_value",
                    models.FloatField(null=True, verbose_name="이전 값"),
                ),
                (
                    "forecast_value",
                    models.FloatField(null=True, verbose_name="예상 값"),
                ),
                ("actual_value", models.FloatField(null=True, verbose_name="실제 값")),
                (
                    "is_released",
                    models.BooleanField(default=False, verbose_name="발표 여부"),
                ),
            ],
            options={
                "verbose_name": "경제 지표",
                "verbose_name_plural": "경제 지표들",
                "ordering": ["-release_date"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("usd_krw", models.FloatField(null=True, verbose_name="USD/KRW")),
                ("eur_usd", models.FloatField(null=True, verbose_name="EUR/USD")),
                ("jpy_krw", models.FloatField(null=True, verbose_name="JPY/KRW")),
            ],
            options={
                "verbose_name": "환율",
                "verbose_name_plural": "환율들",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="MarketIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("sp500", models.FloatField(null=True, verbose_name="S&P 500")),
                ("nasdaq", models.FloatField(null=True, verbose_name="NASDAQ")),
                ("kospi", models.FloatField(null=True, verbose_name="KOSPI")),
                ("kosdaq", models.FloatField(null=True, verbose_name="KOSDAQ")),
                ("vix", models.FloatField(null=True, verbose_name="VIX")),
                ("dxy", models.FloatField(null=True, verbose_name="Dollar Index")),
            ],
            options={
                "verbose_name": "시장 지수",
                "verbose_name_plural": "시장 지수들",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="NewsHeadline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("title", models.CharField(max_length=500, verbose_name="제목")),
                ("source", models.CharField(max_length=100, verbose_name="출처")),
                ("url", models.URLField(verbose_name="링크")),
                (
                    "summary",
                    models.TextField(blank=True, null=True, verbose_name="요약"),
                ),
            ],
            options={
                "verbose_name": "뉴스",
                "verbose_name_plural": "뉴스들",
                "ordering": ["-timestamp"],
            },
        ),
    ]
